# Generated by Django 6.0.5 on 2026-07-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
    ]
