# Generated by Django 6.0.5 on 2026-08-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitems_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='Order',
            new_name='order',
        ),
    ]
