# Generated by Django 6.0.5 on 2026-08-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customer_email_remove_customer_name'),
        ('orders', '0005_rename_order_orderitems_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Deliverd', 'Deliverd'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
