# Generated by Django 6.0.5 on 2026-08-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Deliverd', 'Deliverd'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
